# Site settings
title: Ade da Atmaja
email: sanjaatmaja@live.com
description: > # this means to ignore newlines until "baseurl:"
  Buku catatan dan diary ade da atmaja
tagline: Handsome right?
baseurl: "" # the subpath of your site, e.g. /blog/
author: Ade da Atmaja
url: "http://willy.vulnerability.or.id" # the base hostname & protocol for your site
twitter: sanjaatmaja
github:  sanjaatmaja
facebook: sumpah.akurapopo
video: http://video.vulnerability.or.id
email: willy.arisky@live.com

# Build settings
markdown: kramdown
