# Site settings
title: Vulnerability ID
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Security is just an illusion
tagline: Security is just an illusion
baseurl: "" # the subpath of your site, e.g. /blog/
author: Willy Arisky
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
twitter: WillyArisky
github:  willyarisky
facebook: willy.arisky
video: http://video.vulnerability.or.id
email: willy.arisky@live.com

# Build settings
markdown: kramdown
