# Site settings
title: Willy Arisky
email: willy.arisky@live.com
description: > # this means to ignore newlines until "baseurl:"
  Buku catatan dan diary Willy Arisky 
tagline: Knowledge better than certificate
baseurl: "" # the subpath of your site, e.g. /blog/
author: Willy Arisky
url: "http://willy.vulnerability.or.id" # the base hostname & protocol for your site
twitter: WillyArisky
github:  willyarisky
facebook: willy.arisky
video: http://video.vulnerability.or.id
email: willy.arisky@live.com

# Build settings
markdown: kramdown
